[package]
authors = ["budde25 <ethan@ebudd.io>"]
edition = "2018"
name = "os"
version = "0.1.0"
[dependencies]
bit_field = "*"
bitflags = "*"
spin = "*"
volatile = "*"
delegate = "*"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"

[profile]
[profile.dev]
lto = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[[test]]
harness = false
name = "stack_overflow"
