[package]
authors = ["budde25 <ethan@ebudd.io>"]
edition = "2018"
name = "os"
version = "0.1.0"
[dependencies]
bit_field = "0.10.1"
bitflags = "1.2.1"
spin = "0.9.2"

[dependencies.arrayvec]
default-features = false
version = "0.7.1"

[dependencies.lazy_static]
features = ["spin_no_std"]
version = "1.0"

[profile]
[profile.dev]
lto = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

[[test]]
harness = false
name = "stack_overflow"
